version: '3.8'

services:
  frontend:
    image: ghcr.io/clebergraciano/abralimp-frontend:latest
    # Usa a imagem do registry ao inv√©s de buildar localmente
    ports:
      - "88:80"
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
